name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [lib, examples, tests, benches]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Update Rust toolchain
        run: |
          rustup update stable
          rustup update nightly
          rustup default stable
      
      - name: Check code with all features
        run: |
          cargo check --${{ matrix.target }} --all-features
      
      - name: Check code without any features
        run: |
          cargo check --${{ matrix.target }} --no-default-features
      
      - name: Build docs
        run: |
          cargo +nightly rustdoc --all-features -Z unstable-options -Z rustdoc-scrape-examples -- --generate-link-to-definition --cfg docsrs
  
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [lib, examples, tests, benches]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Update Rust toolchain
        run: |
          rustup update stable
          rustup update nightly
          rustup default stable
          rustup component add rustfmt --toolchain nightly

      - name: Lint code
        run: |
          cargo clippy --${{ matrix.target }} --all-features -- --deny warnings
      
      - name: Format code
        run: |
          cargo +nightly fmt --check
    
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update Rust toolchain
        run: |
          rustup update stable
          rustup default stable
      
      - name: Run tests
        run: |
          cargo test --all-features
